# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant multi-machine sample setup

Vagrant.configure("2") do |config|
  config.vm.define :server do |server|
    server.vm.box = "hashicorp/precise64"
    server.vm.network :private_network, ip: "10.0.0.10"
    server.vm.hostname = "server"
  end

  config.vm.define :client do |client|
    client.vm.box = "hashicorp/precise64"
    client.vm.network :private_network, ip: "10.0.0.11"
    client.vm.hostname = "client"
  end
end
