#!/bin/bash

set -e

[ "${TARGET}" == "" ] && TARGET=/tmp/pyfounder-LIVE_BOOT
[ "${TARGET_HOSTNAME}" == "" ] && TARGET_HOSTNAME=pyfounder
[ "${IMAGE_TARGET_DIR}" == "" ] && IMAGE_TARGET_DIR=$PWD/image
[ "${ARCH}" == "" ] && ARCH=amd64

test -f scripts/setup.sh || { echo "Error: scripts/setup.sh not found."; exit 1 }

# install basic tools necessary to set up a debian system
sudo apt-get install -y \
    debootstrap \
    squashfs-tools

# create target directory
mkdir -p ${TARGET}

# set up baisc target system
test -f ${TARGET}/chroot/bin/bash || sudo debootstrap \
    --arch=${ARCH} \
    --variant=minbase \
    stretch \
    ${TARGET}/chroot \
    http://ftp.de.debian.org/debian/


sudo mkdir -p ${TARGET}/chroot/scripts
sudo cp -a ./scripts/* ${TARGET}/chroot/scripts/

# set hostname
sudo sh -c "echo ${TARGET_HOSTNAME} > ${TARGET}/chroot/etc/hostname"
# run setup
sudo chroot ${TARGET}/chroot /tmp/setup.sh

if [ "${ROOT_TEMPLATE}" != "" ] && [ -d ${ROOT_TEMPLATE} ]; then
    (cd ${ROOT_TEMPLATE}; tar c .) | sudo tar xv -C ${TARGET}/chroot
    sudo chown -R root:root ${TARGET}/chroot/root
fi

# copy chroot environment
sudo rsync -aH --delete-after ${TARGET}/chroot/ ${TARGET}/chroot-final/
# and clean up
chmod +x ${TARGET}/chroot-final/scripts/clean.sh
sudo chroot ${TARGET}/chroot-final /scripts/clean.sh

# create image
mkdir -p ${IMAGE_TARGET_DIR}

# copy kernel and initrd
cp ${TARGET}/chroot/boot/vmlinuz-* \
    ${IMAGE_TARGET_DIR}/vmlinuz && \
cp ${TARGET}/chroot/boot/initrd.img-* \
    ${IMAGE_TARGET_DIR}/initrd

# TODO remove vmlinuz and initrd from chroot-final to free space?
#      or even everything in /boot?

# recreate squashfs
rm -f ${IMAGE_TARGET_DIR}/filesystem.squashfs

sudo mksquashfs \
    ${TARGET}/chroot-final \
    ${IMAGE_TARGET_DIR}/filesystem.squashfs \
    -e boot

exit 0
