#!/bin/bash

set -e

[ "${TARGET}" == "" ] && TARGET=/tmp/pyfounder-LIVE_BOOT
[ "${TARGET_HOSTNAME}" == "" ] && TARGET_HOSTNAME=pyfounder
[ "${IMAGE_TARGET_DIR}" == "" ] && IMAGE_TARGET_DIR=$PWD/image
[ "${ARCH}" == "" ] && ARCH=amd64

test -f scripts/setup.sh || { echo "Error: scripts/setup.sh not found."; exit 1; }

# install basic tools necessary to set up a debian system
sudo apt-get install -y \
    debootstrap \
    squashfs-tools

# create target directory
mkdir -p ${TARGET}

# set up baisc target system
test -f ${TARGET}/chroot/bin/bash || sudo debootstrap \
    --arch=${ARCH} \
    --variant=minbase \
    buster \
    ${TARGET}/chroot \
    http://ftp.de.debian.org/debian/



sudo mkdir -p ${TARGET}/chroot/scripts
sudo cp -a ./scripts/* ${TARGET}/chroot/scripts/

# set hostname
sudo sh -c "echo ${TARGET_HOSTNAME} > ${TARGET}/chroot/etc/hostname"
# run setup
sudo chroot ${TARGET}/chroot /scripts/setup.sh

if [ "${ROOT_TEMPLATE}" != "" ] && [ -d ${ROOT_TEMPLATE} ]; then
    (cd ${ROOT_TEMPLATE}; tar c .) | sudo tar xv -C ${TARGET}/chroot
    sudo chown -R root:root ${TARGET}/chroot/root
fi

# copy chroot environment
sudo rsync -aH --delete-after ${TARGET}/chroot/ ${TARGET}/chroot-final/
# and clean up
chmod +x ${TARGET}/chroot-final/scripts/clean.sh
sudo chroot ${TARGET}/chroot-final /scripts/clean.sh
sudo chown -R root:root ${TARGET}/chroot-final

# create image
mkdir -p ${IMAGE_TARGET_DIR}

set -x

# recreate squashfs
rm -f ${IMAGE_TARGET_DIR}/filesystem.squashfs

T=`mktemp -d`
mkdir -p $T

sudo mksquashfs \
    ${TARGET}/chroot-final \
    $T/filesystem.squashfs \
    -e boot

# copy kernel and initrd
cp -v $(ls -1 ${TARGET}/chroot/boot/vmlinuz-* | tail -1) \
    ${IMAGE_TARGET_DIR}/vmlinuz && \
cp -v $(ls -1 ${TARGET}/chroot/boot/initrd.img-* | tail -1) \
    ${IMAGE_TARGET_DIR}/initrd

cp  ${T}/filesystem.squashfs ${IMAGE_TARGET_DIR}/filesystem.squashfs

sudo rm -rf ${T}

exit 0
