---
globals:

hosts:
  example1:
    interface: enp0s8
    mac: 00:d8:61:2d:6d:bb
    ip: 10.0.0.2
    class: workstation

  example2:
    interface: enp0s8
    mac: 00:d8:61:2d:6d:bb
    ip: 10.0.0.2
    class: workstation

classes:
  default: 
    templates: &default_temlates
      #pxelinux.cfg: pxe/localhdd
      pxelinux.cfg-install: pxe/install-bionic
      pxelinux.cfg: pxe/install-bionic
      preseed.cfg: pressed.cfg/default
      early_command:
      late_command:
      first_boot:
    variables: &default_variables
      test: one
      apt-proxy: http://apt-cacher-ng:3142
  # the class for all workstations
  workstation: &workstation
    templates:
      <<: *default_temlates
    variables:
      <<: *default_variables
      test: two

# vim: set ts=2 sts=2 sw=2 et:
